name: "Feature Request"
description: Think BuffOverlay needs something? Let me know!
# title: "[BUG]: "
labels: ["enhancement"]
assignees:
  - clicketz
body:
- type: markdown
  attributes:
    value: |
      Please [search for existing requests](https://github.com/clicketz/buff-overlay/labels/enhancement) before creating a new one.

- type: textarea
  attributes:
    label: Description
    description: What would you like to see added to BuffOverlay?
  validations:
    required: true

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help me understand your request.
    placeholder: Click here to attach your screenshots via the editor button in the top right.
  validations:
    required: false
